# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('codigo', models.PositiveIntegerField()),
                ('proveedor', models.CharField(max_length=100)),
                ('precio_compra', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('stock', models.PositiveIntegerField()),
                ('stock_minimo', models.PositiveIntegerField()),
                ('stock_maximo', models.PositiveIntegerField()),
            ],
        ),
    ]
