# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 03:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cedula', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('telefono', models.CharField(max_length=15)),
                ('cargo', models.CharField(choices=[('Departamento de Recepcion', 'Departamento de Recepcion'), ('Empleado', 'Empleado'), ('Administrador', 'Administrador')], default='Empleado', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
